"""Add Winners table

Revision ID: 837e34363789
Revises: 
Create Date: 2025-01-23 15:25:16.078002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837e34363789'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('won_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winner')
    # ### end Alembic commands ###
