"""Added/Updated tables

Revision ID: 998175e11200
Revises: 31b0ab9cdcba
Create Date: 2025-01-25 19:44:03.073094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998175e11200'
down_revision = '31b0ab9cdcba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
